### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Einsy** [bnoordhuis/node-buffertools#85] opened 2017-03-29 06:45 UTC
win8.1
vs2015
x64
node6.9.4

build error

G:\FastCache\node-buffertools>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@6.9.4 | win32 | x64
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Users\Administrator\.node-gyp\6.9.4\Release\node.lib : fatal error LNK1106:
文件无效或磁盘已满:  无法查找到 0x645B0 [G:\FastCache\node-buffertools\build\buf
fertools.vcxp
roj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roamin
g\npm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.3.9600

**Comment by bnoordhuis** [comment] 2017-03-29 11:46
Closing, duplicate of #84.

**Closed by bnoordhuis** 2017-03-29 11:46 UTC
